/*
* This code has been generated by the Rebel: a Model Driven Development Toolkit for Java,
* provided by the Archetype Software Engineering.
*
* Drop us a mail at contact@archetypesoftware.com or visit www.archetypesoftware.com
* if you need additional information or have any questions.
*/
package com.manning.readinglist.domainconcepts;

import java.util.*;
import java.time.*;

import javax.persistence.*;
import javax.validation.constraints.*;


// ----------- << imports@AAAAAAFiblU/qnPuW3U= >>
// ----------- >>

@Entity
// ----------- << class.annotations@AAAAAAFiblU/qnPuW3U= >>
// ----------- >>
public class Book {
    // ----------- << id.annotations@AAAAAAFiblU/qnPuW3U= >>
    // ----------- >>
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    private Long id;

    // ----------- << version.annotations@AAAAAAFiblU/qnPuW3U= >>
    // ----------- >>
    @Version
    private Long version;

    @NotNull
    @Column(nullable=false)
    // ----------- << attribute.annotations@AAAAAAFible7D3QfDEY= >>
    // ----------- >>
    private String title;

    @NotNull
    @Column(nullable=false)
    // ----------- << attribute.annotations@AAAAAAFiblfJ53Qmwfk= >>
    // ----------- >>
    private String author;

    @Column
    // ----------- << attribute.annotations@AAAAAAFifLZ7AQRhJgs= >>
    // ----------- >>
    private String description;

    @Column
    // ----------- << attribute.annotations@AAAAAAFiblfZ0nQtp2M= >>
    // ----------- >>
    private String reader;

    @Column
    // ----------- << attribute.annotations@AAAAAAFiblfk8XQ0e08= >>
    // ----------- >>
    private String isbn;

    // ----------- << getId.annotations@AAAAAAFiblU/qnPuW3U= >>
    // ----------- >>
    public Long getId(){
        return id;
    }

    public String getTitle() {
        return title;
    }

    public String getAuthor() {
        return author;
    }

    public String getDescription() {
        return description;
    }

    public String getReader() {
        return reader;
    }

    public String getIsbn() {
        return isbn;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setReader(String reader) {
        this.reader = reader;
    }

    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    // ----------- << equals.annotations@AAAAAAFiblU/qnPuW3U= >>
    // ----------- >>
    @Override
    public boolean equals(Object obj) {
        if (super.equals(obj)) return true;
        if (getId() == 0) return false;
        return obj instanceof Book && (getId() == ((Book) obj).getId());
    }

// ----------- << class.extras@AAAAAAFiblU/qnPuW3U= >>
// ----------- >>
}