/*
* This code has been generated by the Rebel: a Model Driven Development Toolkit for Java,
* provided by the Archetype Software Engineering.
*
* Drop us a mail at contact@archetypesoftware.com or visit www.archetypesoftware.com
* if you need additional information or have any questions.
*/
package com.manning.readinglist.domainconcepts;

import java.util.*;
import java.time.*;

import javax.persistence.*;
import javax.validation.constraints.*;


// ----------- << imports@AAAAAAFifPbYAOeeRUw= >>
// ----------- >>

/**
* Represents a reader, registered within the application.
*/

@Entity
// ----------- << class.annotations@AAAAAAFifPbYAOeeRUw= >>
// ----------- >>
public class Reader {
    // ----------- << id.annotations@AAAAAAFifPbYAOeeRUw= >>
    // ----------- >>
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    private Long id;

    // ----------- << version.annotations@AAAAAAFifPbYAOeeRUw= >>
    // ----------- >>
    @Version
    private Long version;

    /**
    * Username, used to authenticate to the application.
    */

    @NotNull
    @Column(unique=true, nullable=false)
    // ----------- << attribute.annotations@AAAAAAFifPcon+fOJdw= >>
    // ----------- >>
    private String username;

    @NotNull
    @Column(nullable=false)
    // ----------- << attribute.annotations@AAAAAAFifPdI4+fVx5c= >>
    // ----------- >>
    private String fullname;

    /**
    * Users password.
    */

    @NotNull
    @Column(nullable=false)
    // ----------- << attribute.annotations@AAAAAAFifPduZ+fc4c8= >>
    // ----------- >>
    private String password;

    // ----------- << getId.annotations@AAAAAAFifPbYAOeeRUw= >>
    // ----------- >>
    public Long getId(){
        return id;
    }

    public String getUsername() {
        return username;
    }

    public String getFullname() {
        return fullname;
    }

    public String getPassword() {
        return password;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    // ----------- << equals.annotations@AAAAAAFifPbYAOeeRUw= >>
    // ----------- >>
    @Override
    public boolean equals(Object obj) {
        if (super.equals(obj)) return true;
        if (getId() == 0) return false;
        return obj instanceof Reader && (getId().equals(((Reader) obj).getId()));
    }

// ----------- << class.extras@AAAAAAFifPbYAOeeRUw= >>
// ----------- >>
}