/*
* This code has been generated by the Rebel: a Model Driven Development Toolkit for Java,
* provided by the Archetype Software Engineering.
*
* Drop us a mail at contact@archetypesoftware.com or visit www.archetypesoftware.com
* if you need additional information or have any questions.
*/
package com.manning.readinglist.repositories;

import java.util.*;
import java.time.*;


import com.manning.readinglist.domainconcepts.Book;
import org.springframework.data.repository.*;
import org.springframework.stereotype.Repository;
// ----------- << preserved-imports
import org.springframework.data.jpa.repository.JpaRepository;
// ----------- >>

// ----------- << AAAAAAFiblU/qnPuW3U=>annotations
// ----------- >>
@Repository
public interface BookRepository extends JpaRepository<Book, Long> {
// ----------- << AAAAAAFiblU/qnPuW3U=>repositoryMethods
    List<Book> findByReader(String reader);
// ----------- >>
}