/*
* This code has been generated by the Rebel: a Model Driven Development Toolkit for Java,
* provided by the Archetype Software Engineering.
*
* Drop us a mail at contact@archetypesoftware.com or visit www.archetypesoftware.com
* if you need additional information or have any questions.
*/
package com.manning.readinglist.controllers;

import java.util.*;
import java.time.*;

import org.springframework.stereotype.Controller;

import com.manning.readinglist.domainconcepts.Book;
// ----------- << imports@AAAAAAFibltVb3RBh+A= >>
import com.manning.readinglist.repositories.BookRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
// ----------- >>

/**
* Controller for the Book concept.
*/

@RequestMapping("/")
@Controller
// ----------- << class.annotations@AAAAAAFibltVb3RBh+A= >>
// ----------- >>
public class BookController {
    /**
    * @param reader 
    * @param model
    */

    @GetMapping(value="/{reader}")
    // ----------- << method.annotations@AAAAAAFiblx0pXRxF5o= >>
    // ----------- >>
    public String readersBooks(@PathVariable("reader") String reader, Model model) {
    // ----------- << method.body@AAAAAAFiblx0pXRxF5o= >>
        List<Book> readingList = bookRepository.findByReader(reader);
        if (readingList != null) {
            model.addAttribute("books", readingList);
        }
        return "readingList";
    // ----------- >>
    }
    /**
    * @param reader 
    * @param book
    */

    @PostMapping("/{reader}")
    // ----------- << method.annotations@AAAAAAFibmKMZ3SHQCU= >>
    // ----------- >>
    public String addToReadingList(@PathVariable("reader") String reader, Book book) {
    // ----------- << method.body@AAAAAAFibmKMZ3SHQCU= >>
        book.setReader(reader);
        bookRepository.save(book);
        return "redirect:/{reader}";
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAFibltVb3RBh+A= >>
    @Autowired
    BookRepository bookRepository;
// ----------- >>
}